# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7ec2e99a6149b89902e3622d40893ee2f63084a35bef2e488ab10238c76a8c53b722a3b433240db7760a6a91c6f22a3edb30d7ba8c3e82dcae294a2852e506c

test:
  secret_key_base: c28eafc53186036df71575ee7fbeba477eca49ca3d5ad82138a0b72e18b207cef5440a74a85f896b436a816e678cf6e059cfdc099971017b9a9114dfd1c395eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
